# Usa una imagen base de Python ligera.
FROM python:3.9-slim

# Define el directorio de trabajo dentro del contenedor.
WORKDIR /app

# Copia la carpeta 'dependencies' completa a tu contenedor.
# Esta carpeta debe contener todos los archivos .whl correctos.
COPY ./dependencies /app/dependencies
RUN pip install --no-index --find-links /app/dependencies/ /app/dependencies/python_snap7-2.0.2-py3-none-manylinux_2_28_x86_64.whl -r /app/dependencies/requirements-plc.txt

# Instala todas las dependencias desde los archivos locales.
# Usa --no-index para evitar la conexión a internet.
# Usa --find-links para buscar en el directorio de dependencias.
RUN pip install --no-index --find-links /app/dependencies/ -r /app/dependencies/requirements-plc.txt

# Copia el script principal de tu aplicación.
COPY plc_to_kafka_snap7_off.py .

# Define el comando que se ejecutará al iniciar el contenedor.
CMD ["python", "plc_to_kafka_snap7_off.py"]