# Usa una imagen base de Python ligera.
FROM python:3.9-slim

# Define el directorio de trabajo dentro del contenedor.
WORKDIR /app

# Copia la carpeta 'dependencies' completa a tu contenedor.
COPY ./dependencies /app/dependencies

# Instala las dependencias de Python desde el directorio local.
# Nota: Este requirements-plc.txt ya NO debe tener la línea de "python-snap7".
RUN pip install --no-index --find-links /app/dependencies/ -r /app/dependencies/requirements-plc.txt

# Instala snap7 directamente desde el repositorio que copiaste.
RUN pip install /app/dependencies/python-snap7

# Instala las dependencias del sistema operativo que AÚN necesitan internet.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    python3-dev \
    libsnap7-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia el script principal de tu aplicación.
COPY plc_to_kafka_snap7_off.py .

# Define el comando que se ejecutará al iniciar el contenedor.
CMD ["python", "plc_to_kafka_snap7_off.py"]